version: 2.1

orbs:
  vfcommon: voiceflow/common@0.48.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  test:
    executor: vfcommon/code-test-executor-node-20
    steps:
      - checkout
      - vfcommon/install_node_modules:
          cache_prefix: v1
      - attach_workspace:
          at: ~/voiceflow
      - vfcommon/lint_report:
          run_in_background: true
      - vfcommon/dependency_tests:
          run_in_background: true
      - vfcommon/integration_tests:
          wait: true
      - sonarcloud/scan

workflows:
  test-and-release:
    jobs:
      - vfcommon/install_and_build:
          context: dev-test

      - test:
          context: dev-test
          requires:
            - vfcommon/install_and_build

      - vfcommon/release:
          context: dev-test
          requires:
            - test
            - vfcommon/install_and_build
          filters:
            branches:
              only: master
