version: 2.1

# Reusable YAML chunks
defaults:
  autorebase_filters: &autorebase_filters
    branches:
      ignore:
        - /rebase-pull-request-.*/
        - /cherry-pick-rebase-pull-request-.*/

orbs:
  codecov: codecov/codecov@1.0.2
  vfcommon: voiceflow/common@0.0.67

jobs:
  build-and-test:
    executor: vfcommon/default-executor
    steps:
      - checkout
      - vfcommon/install_node_modules
      - vfcommon/lint_source
      - vfcommon/dependency_tests:
          step_name: Dependency Tests
      - vfcommon/build
      - vfcommon/integration_tests
      - codecov/upload:
          file: nyc_coverage/lcov.info
          flags: integration

workflows:

  test-and-release:
    jobs:
      - build-and-test:
          filters:
            <<: *autorebase_filters
            
      - vfcommon/release:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
